version: '3'

services:
  app:
    container_name: calendar-demo-app-dev
    image: calendar-demo-app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    stdin_open: true
    ports:
      - 3000:3000
